name: First Workflow

on: push

jobs:
    first_job:
        runs-on: [jumpsrv-ubuntu, test]
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: List files and readme
          run: |
            echo "This is first github action output"
            ls -ltra
            cat README.md
      

#        - name: List Files
 #         run: ls

  #      - name: Read file
   #       run: cat README.md
