name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "This is first github action output"

        - name: List Files
          run: ls

        - name: Read file
          run: cat README.md
