name: Testing self hosted runner
on: 
  workflow_dispatch:

jobs:
  testing:
    runs-on: [self-hosted,Linux,X64,prod,main]
    steps:
      - name: Echo content
        run: |
          echo "welcome"
          sleep 30s
